### ISSUE TITLE
AttributeError: 'Pose' object has no attribute 'detect'

### ISSUE THREAD

**Issue by 223528lq** [IS2AI/OpenThermalPose#1]

**Comment by akuzdeuov** [comment]
Hello! 
This may be due to inconsistencies between the version of Ultralytics. Please consider upgrading it to the latest version: 
```
pip install --upgrade ultralytics
```
If it does not resolve the issue please provide more detailed information.

**Comment by akuzdeuov** [comment]
I am closing the issue but feel free to open it if the problem is not solved.
