### ISSUE TITLE
Can it be used for far infrared? The sensory effect is not good.

### ISSUE THREAD

**Issue by 223528lq** [IS2AI/OpenThermalPose#2]

**Comment by akuzdeuov** [comment]
Hello! 

If you mean the models then yes they can be applied for far infrared images as one of the cameras (FLIR T540) used for data collection operates in 7.5 - 14 µm spectral range.

**Comment by 223528lq** [comment]
> 你好！
> 
> 如果您指的是模型，那么是的，它们可以应用于远红外图像，因为用于数据收集的相机之一 （FLIR T540） 在 7.5 - 14 μm 的光谱范围内工作。

Why can't I identify key points on human images captured by my infrared camera? My infrared images are for medical purposes, infrared thermography, do I need to modify any parameters? Thank you for your reply.

**Comment by 223528lq** [comment]
> > 你好！
> > 如果您指的是模型，那么是的，它们可以应用于远红外图像，因为用于数据收集的相机之一 （FLIR T540） 在 7.5 - 14 μm 的光谱范围内工作。
> 
> 为什么我无法识别红外相机拍摄的人体图像上的关键点？我的红外图像用于医疗目的，红外热成像，我需要修改任何参数吗？谢谢你的回复。

Correction: Infrared thermal tomography

**Comment by akuzdeuov** [comment]
What is the resolution of your camera? If possible, could you please share one example image?

**Comment by 223528lq** [comment]
> 您的相机的分辨率是多少？如果可能的话，您能分享一张示例图片吗？

![b04039399257ea6df4f60f424fdedd5](https://github.com/user-attachments/assets/1a80a82f-388e-4e54-a7d5-751c666f8140)
Of course. The camera resolution is 640.

**Comment by akuzdeuov** [comment]
Thanks for sharing. I applied the models to the image but they couldn't detect the person. I guess this may be due to saturated pixel values on the back of the person. I simply painted this area and the model could detect the person but with a low confidence. So I would suggest to apply some image processing methods to enhance the image and then apply the model. An alternative option would be to collect some amount of images and fine-tune one of the models. However, this requires manual labeling.   

![image0](https://github.com/user-attachments/assets/6b1aa683-41bc-4041-99e7-ccb8362aec29)

**Comment by 223528lq** [comment]
> 感谢分享。我将模型应用于图像，但它们无法检测到这个人。我猜这可能是由于人背部的饱和像素值。我简单地画了这个区域，模型可以检测到这个人，但置信度很低。所以我建议应用一些图像处理方法来增强图像，然后应用模型。另一种选择是收集一定数量的图像并微调其中一个模型。但是，这需要手动标记。
> 
> ![图片0](https://private-user-images.githubusercontent.com/39990260/388829998-6b1aa683-41bc-4041-99e7-ccb8362aec29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDYxMzIsIm5iZiI6MTczMjYwNTgzMiwicGF0aCI6Ii8zOTk5MDI2MC8zODg4Mjk5OTgtNmIxYWE2ODMtNDFiYy00MDQxLTk5ZTctY2NiODM2MmFlYzI5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA3MjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMzY3MTRkNjA4NDJhZDdhMTVlMmYzODVmOGUwODNjZmUwNjczMTVkYTNmMjFiMmE1NzZjZmI2MGQ0MjMzMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jx5FC1beu3aZfgzlEt4EC1LupJxOQNGeYi7fTgQVs-A)

Okay, thank you for your response.

**Comment by akuzdeuov** [comment]
I am closing the issue but feel free to open it if you will have questions.
